spring:
  datasource:
    url: jdbc:mysql://47.99.95.4:3306/mineral?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  data:
    mongodb:
      host: 47.99.95.4
      port: 27017
      database: Mineral
  redis:
    host: 47.99.95.4 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 515515 # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 47.99.95.4
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost
alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl:
